#!/bin/sh
set -e
set -x

[ $# -ge 1 ] || exit 1

pkgname="$1"

shift

if [ `ulimit` -lt 2000000 ]; then
	ulimit 2000000
fi

[ -d /u/root/src/$pkgname ] || exit 1

ls -l incs
pwd
cat incs
. ./incs

cd /u/root/src/$pkgname

if [ ! -z "$MAKE_SUBDIR" ]; then
	cd $MAKE_SUBDIR
fi

/usr/local/bin/make "$@"
